import donWorriedAsset from "@/assets/DON_worried.png.asset.json";
import donHappyAsset from "@/assets/DON_happy.png.asset.json";
import donDisappointedAsset from "@/assets/DON_disappointed.png.asset.json";
import donAngryAsset from "@/assets/DON_angry.png.asset.json";
import type { CatastropheDef, CatastropheOutcome, CatastropheTally } from "@/game/catastrophes";
import type { ShiftObjective } from "@/game/objectives";
import { miniGameByKey } from "@/game/minigames";
import { cn } from "@/lib/utils";

export function DonBubble({ line }: { line: string }) {
  return <div className="pointer-events-none absolute left-1/2 top-[2%] z-[45] flex -translate-x-1/2 flex-col items-center" aria-label="The DON is on the ward"><div className="animate-pop max-w-[220px] rounded-2xl border-2 border-border bg-card px-2.5 py-1 text-center shadow-lg"><p className="font-display text-[11px] font-black uppercase leading-tight">{line}</p></div><span className="animate-bob mt-0.5 grid h-11 w-11 place-items-center rounded-full border-2 border-alarm bg-card text-2xl shadow-lg ring-4 ring-alarm/30">🧑‍💼</span><span className="font-display rounded-full bg-alarm px-1.5 text-[8px] font-black uppercase text-alarm-foreground">DON</span></div>;
}

export function ShiftBriefing({ level, name, title, lead, objectives, onStart }: { level: number; name: string; title: string; lead: string; objectives: ShiftObjective[]; onStart: () => void }) {
  return <div className="absolute inset-0 z-[70] grid place-items-center bg-background/85 p-4 backdrop-blur-sm"><div className="animate-pop w-full rounded-3xl border-4 border-border bg-card p-4 shadow-2xl"><p className="font-display text-center text-[11px] font-black uppercase tracking-widest text-primary">Shift {level} · {name}</p><h3 className="font-display mt-1 text-center text-2xl font-black uppercase leading-none">“{title}”</h3><p className="mt-1 text-center text-sm font-semibold text-muted-foreground">{lead}</p><p className="font-display mt-3 text-center text-[11px] font-black uppercase tracking-widest text-muted-foreground">This shift's challenges</p><div className="mt-3 space-y-2">{objectives.map((objective) => <div key={objective.key} className="flex items-center gap-2 rounded-2xl border-2 border-border bg-background px-2.5 py-2"><span className="text-2xl leading-none">{objective.icon}</span><span className="min-w-0 flex-1 text-sm font-bold leading-tight">{objective.label}</span><span className="font-display shrink-0 rounded-full bg-gold px-2 py-0.5 text-xs font-black text-gold-foreground">+{objective.reward.amount} {objective.reward.type === "points" ? "⭐" : "✨"}</span></div>)}</div><button onClick={onStart} className="chunky chunky-press mt-4 w-full rounded-2xl bg-primary py-4 font-display text-xl font-black uppercase text-primary-foreground">Start shift ▶</button></div></div>;
}

export function CatastropheIntro({ catastrophe, buttonLabel, onStart }: { catastrophe: CatastropheDef; buttonLabel: string; onStart: () => void }) {
  return <div className="absolute inset-0 z-[90] grid place-items-center bg-background/90 p-4 backdrop-blur-sm"><div className="animate-pop w-full max-w-sm rounded-3xl border-4 border-alarm bg-card p-4 text-center shadow-2xl"><img src={donWorriedAsset.url} alt="Worried Director of Nursing" className="mx-auto h-40 w-auto object-contain [image-rendering:pixelated]"/><p className="font-display mt-1 text-sm font-black uppercase text-alarm">🚨 Catastrophic Event 🚨</p><h3 className="font-display mt-1 text-3xl font-black uppercase leading-none">{catastrophe.intro.title}</h3>{catastrophe.intro.lines.map((line, index) => <p key={line} className={`${index === 0 ? "mt-3" : "mt-2"} text-sm font-bold`}>“{line}”</p>)}<p className="mt-2 text-sm font-black">“{catastrophe.intro.closing}”</p><button onClick={onStart} className="chunky chunky-press mt-4 w-full rounded-2xl bg-alarm py-4 font-display text-xl font-black uppercase text-alarm-foreground">{buttonLabel}</button></div></div>;
}

export function CatastropheConclusion({ result, tally }: { result: { outcome: CatastropheOutcome; title: string; line: string }; tally: CatastropheTally }) {
  const portrait = result.outcome === "positive" ? donHappyAsset.url : result.outcome === "neutral" ? donDisappointedAsset.url : donAngryAsset.url;
  return <div className="absolute inset-0 z-[90] grid place-items-center bg-background/90 p-4 backdrop-blur-sm"><div className={cn("animate-pop w-full max-w-sm rounded-3xl border-4 bg-card p-4 text-center shadow-2xl", result.outcome === "positive" ? "border-calm" : result.outcome === "neutral" ? "border-gold" : "border-alarm")}><img src={portrait} alt="Director of Nursing" className="mx-auto h-44 w-auto object-contain [image-rendering:pixelated]"/><h3 className="font-display text-2xl font-black uppercase leading-none">{result.title}</h3><p className="mt-3 text-base font-bold">DON: “{result.line}”</p><p className="mt-3 text-xs font-bold uppercase opacity-70">{tally.generated} problems · {tally.best} best · {tally.sortOf} sort of · {tally.worst} worst · {tally.missed} missed</p></div></div>;
}

export function ReadyCue({ cue }: { cue: string }) { return <div className="absolute inset-0 z-50 grid place-items-center bg-background/80 backdrop-blur-sm"><p key={cue} className="font-display animate-pop text-center text-5xl font-black uppercase leading-none text-primary">{cue}</p></div>; }
export function EndCountdown({ count }: { count: number }) { return <div className="pointer-events-none absolute inset-0 z-50 grid place-items-center"><div className="text-center"><p className="font-display text-xl font-black uppercase tracking-widest text-primary drop-shadow-[0_2px_0_var(--color-background)]">Shift finishes in</p><p key={count} className="font-display animate-pop text-[7rem] font-black leading-none text-primary drop-shadow-[0_4px_0_var(--color-background)]">{count}</p></div></div>; }

export function TutorialOverlay({ step, onNext }: { step: 0 | 2; onNext: () => void }) {
  const first = step === 0;
  return <div className="absolute inset-0 z-[65] grid place-items-center bg-background/80 p-5 backdrop-blur-sm"><div className="animate-pop w-full rounded-3xl border-4 border-border bg-card p-4 text-center shadow-2xl"><p className="font-display text-[11px] font-black uppercase tracking-widest text-primary">{first ? "First shift? Ten-second tour" : "She's on her way"}</p><h3 className="font-display mt-1 text-3xl font-black uppercase leading-none">{first ? "Your job 🏥" : "Read, then respond 💬"}</h3><p className="mt-3 text-base font-bold">{first ? "Keep every patient stable until the shift timer runs out." : "When she arrives you'll see what's wrong — pick the response that fits."}</p><p className="mt-1 text-base font-semibold text-muted-foreground">{first ? "When a bay lights up or rings the bell, someone needs you." : "The best answer pays full points. Others pay half, nothing, or even cost you — revealed only after you choose. Judge, don't guess!"}</p><button onClick={onNext} className="chunky chunky-press mt-4 w-full rounded-2xl bg-primary py-4 font-display text-xl font-black uppercase text-primary-foreground">Got it ▶</button></div></div>;
}

export function MiniOfferOverlay({ offer, onSkip, onStart }: { offer: { kind: string; bonus: number; lvl: number }; onSkip: () => void; onStart: () => void }) {
  const game = miniGameByKey(offer.kind);
  return <div className="absolute inset-0 z-50 grid place-items-center bg-background/85 p-5 backdrop-blur-sm"><div className="animate-pop w-full rounded-3xl border-4 border-border bg-card p-4 text-center shadow-2xl"><p className="font-display text-[11px] font-black uppercase tracking-widest text-primary">Bonus round available</p><h3 className="font-display text-2xl font-black uppercase leading-none">{game.name}</h3><p className="mt-1 text-sm font-bold">{game.blurb}</p><p className="font-display mt-2 rounded-2xl bg-[image:var(--gradient-gold)] py-2 text-xl font-black text-gold-foreground">Reward: up to +{offer.bonus} ⭐</p><p className="font-display mt-1 text-sm font-black uppercase text-calm-foreground">+ 12 ✨ XP for finishing it</p><p className="mt-2 text-[11px] text-muted-foreground">A small bonus on top of your shift — finish it for the full reward. The ward keeps ticking at 1/3 speed and you can abandon any time.</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={onSkip} className="chunky chunky-press rounded-2xl bg-secondary py-3 font-display text-lg font-black uppercase text-secondary-foreground">Skip</button><button onClick={onStart} className="chunky chunky-press rounded-2xl bg-primary py-3 font-display text-lg font-black uppercase text-primary-foreground">Start ▶</button></div></div></div>;
}

export function PauseOverlay({ line, onResume }: { line: string; onResume: () => void }) { return <div className="absolute inset-0 z-[60] flex flex-col items-center justify-center gap-3 bg-background/85 px-6 text-center backdrop-blur-sm"><p className="font-display text-4xl font-black uppercase">Paused</p><p className="text-sm font-semibold text-muted-foreground">{line}</p><button onClick={onResume} className="chunky chunky-press rounded-2xl bg-primary px-8 py-4 font-display text-xl font-black uppercase text-primary-foreground">Resume ▶</button></div>; }

function SettingRow({ label, icon, on, onToggle }: { label: string; icon: string; on: boolean; onToggle: () => void }) { return <button onClick={onToggle} className="flex w-full items-center justify-between gap-2 rounded-2xl border-2 border-border bg-background px-3 py-3"><span className="font-display flex items-center gap-2 text-base font-black uppercase"><span className="text-xl">{icon}</span>{label}</span><span className={cn("font-display rounded-xl px-3 py-1 text-sm font-black", on ? "bg-calm text-calm-foreground" : "bg-muted text-muted-foreground")}>{on ? "ON" : "OFF"}</span></button>; }

export function SettingsOverlay({ soundOn, musicOn, hapticsOn, autoSaveOn, onToggleAll, onToggleSound, onToggleMusic, onToggleHaptics, onToggleAutoSave, onSave, onQuit, onClose }: { soundOn: boolean; musicOn: boolean; hapticsOn: boolean; autoSaveOn: boolean; onToggleAll: () => void; onToggleSound: () => void; onToggleMusic: () => void; onToggleHaptics: () => void; onToggleAutoSave: () => void; onSave: () => void; onQuit: () => void; onClose: () => void }) {
  return <div className="absolute inset-0 z-[70] grid place-items-center bg-background/90 p-5 backdrop-blur-sm"><div className="w-full space-y-2 rounded-3xl border-4 border-border bg-card p-4"><h3 className="font-display text-2xl font-black uppercase">Settings</h3><SettingRow label="All sound" icon="🔊" on={soundOn && musicOn} onToggle={onToggleAll}/><SettingRow label="Game sounds" icon="🎮" on={soundOn} onToggle={onToggleSound}/><SettingRow label="Music" icon="🎵" on={musicOn} onToggle={onToggleMusic}/><SettingRow label="Haptics" icon="📳" on={hapticsOn} onToggle={onToggleHaptics}/><SettingRow label="Auto-save" icon="💾" on={autoSaveOn} onToggle={onToggleAutoSave}/><div className="grid grid-cols-2 gap-2"><button onClick={onSave} className="chunky chunky-press rounded-2xl bg-secondary py-3 font-display text-lg font-black uppercase text-secondary-foreground">💾 Save</button><button onClick={onQuit} className="chunky chunky-press rounded-2xl bg-alarm py-3 font-display text-lg font-black uppercase text-alarm-foreground">🚪 Quit</button></div><button onClick={onClose} className="chunky chunky-press w-full rounded-2xl bg-primary py-3 font-display text-lg font-black uppercase text-primary-foreground">Back to shift</button></div></div>;
}
